version: 2

sources:
  - name: world_cup
    description: Player and Club informationd for the world cups
    database: dbtweek
    tables:
      - name: world_cup
        description: Source world cup data for our project
        columns:
          - name: Player
            description: Player names as index
            tests:
              - unique
              - not_null