version: 2

sources:
  - name: world_cup
    description: pLAYER AND CLUB INFORMATION FOR THE WORLD CUP
    database: dbtweek
    tables:
      - name: world_cup
        description: Source data for our project
        columns:
          - name: Player
            description: Player names as index
            tests:
              - unique
              - not_null